
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author hapav
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Order = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ShipM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Segment = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        State = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Product = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ProductN = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Sales = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Quantity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Discount = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Profit = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        OrderD = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Costumer = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Country = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Postal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Category = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ShipD = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        CustumerN = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        City = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Region = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        SCategory = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jProgressBar3 = new javax.swing.JProgressBar();
        jPanel3 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        C_textArea = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        C_Tabla = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jProgressBar2 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Order Id:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ship mode:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Segment:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("State:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Product Id:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Product Name:");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Sales");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Quantity:");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Discount:");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Profit");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Order Date:");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Costumer Id:");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Country:");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Postal Code:");

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Category:");

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Ship Date:");

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Costumer Name:");

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("City");

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Region");

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Sub-Category");

        jButton1.setText("Agregar Registro");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jProgressBar3.setBorderPainted(false);
        jProgressBar3.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ShipM)
                                            .addComponent(Order)
                                            .addComponent(jProgressBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Product, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                            .addComponent(State)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Segment, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addGap(9, 9, 9))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel12))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Country, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addComponent(Category)
                                    .addComponent(Postal, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Costumer)
                                    .addComponent(OrderD))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel20)
                                            .addGap(9, 9, 9))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel18)
                                                .addComponent(jLabel19)
                                                .addComponent(jLabel17))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(SCategory)
                                                .addComponent(Region, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(1, 1, 1))
                                        .addComponent(ShipD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(CustumerN, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Sales)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Discount, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Profit, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ProductN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(429, 429, 429)
                        .addComponent(jButton1)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CustumerN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ShipD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Region, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(OrderD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Costumer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Postal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Order, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ShipM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Segment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(State, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 32, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Profit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addGap(76, 76, 76))
        );

        jTabbedPane1.addTab("Agregar Registro", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jProgressBar1.setBorderPainted(false);
        jProgressBar1.setOpaque(true);

        jButton2.setText("Clear");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        C_textArea.setColumns(20);
        C_textArea.setRows(5);
        jScrollPane1.setViewportView(C_textArea);

        jButton3.setBackground(new java.awt.Color(0, 153, 0));
        jButton3.setText("Orders");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(51, 51, 255));
        jButton4.setText("Products");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 0, 51));
        jButton5.setText("Customers");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 153, 0));
        jButton6.setText("Details");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Listar Registro", jPanel3);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        C_Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Row ID", "Order ID", "Order Data", "Customer Id", "Country", "City", "Product Id", "Sales"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(C_Tabla);

        jButton7.setText("Update");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("Eliminar");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton9.setText("Listar");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(422, 422, 422)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar Registro", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        Dba db = new Dba("./DATA.mdb");
        db.conectar();
        
        UIManager.put("nimbusOrange", color2);

        final Timer timer = new Timer(40, new ActionListener() {
            int progress = 0;
            int maxProgress = 5000;

            @Override
            public void actionPerformed(ActionEvent e) {

                if (progress <= maxProgress) {
                    jProgressBar3.setValue(progress * 100 / maxProgress);
                    progress += 50;
                } else {
                    ((Timer) e.getSource()).stop();
                    JOptionPane.showMessageDialog(jPanel4, "Ejecucion completa sin errores");
                    try {
                        String orderID = Order.getText();
                        Order.setText(" ");

                        String orderD = OrderD.getText();
                        OrderD.setText(" ");

                        String shipD = ShipD.getText();
                        ShipD.setText(" ");

                        String shipM = ShipM.getText();
                        ShipM.setText(" ");

                        String customerID = Costumer.getText();
                        Costumer.setText(" ");

                        String customerN = CustumerN.getText();
                        CustumerN.setText(" ");

                        String segment = Segment.getText();
                        Segment.setText(" ");

                        String country = Country.getText();
                        Country.setText(" ");

                        String city = City.getText();
                        City.setText(" ");

                        String state = State.getText();
                        State.setText(" ");

                        String postal = Postal.getText();
                        Postal.setText(" ");

                        String region = Region.getText();
                        Region.setText(" ");

                        String productID = Product.getText();
                        Product.setText(" ");

                        String category = Category.getText();
                        Category.setText(" ");

                        String Scategory = SCategory.getText();
                        SCategory.setText(" ");

                        String productn = ProductN.getText();
                        ProductN.setText(" ");

                        String sales = Sales.getText();
                        Sales.setText(" ");

                        String quantity = Quantity.getText();
                        Quantity.setText(" ");

                        String discount = Discount.getText();
                        Discount.setText(" ");

                        String profit = Profit.getText();
                        Profit.setText(" ");

                        String ID = "11";

                        try {
                            db.query.execute("INSERT INTO TenRecord "
                                    + "([Row ID], [Order ID], [Order Date], [Ship Date], [Ship Mode], [Customer ID], [Customer Name], Segment, Country, City, State, [Postal Code], Region, [Product ID], Category, [Sub-Category], [Product Name], Sales, Quantity, Discount, Profit)"
                                    + " VALUES ('" + ID + "', '" + orderID + "', '" + orderD + "', '" + shipD + "', '" + shipM + "', '" + customerID + "', '" + customerN + "', '" + segment + "', '" + country + "', '" + city + "', '" + state + "', '" + postal + "', '" + region + "', '" + productID + "', '" + category + "', '" + Scategory + "', '" + productn + "', '" + sales + "', '" + quantity + "', '" + discount + "', '" + profit + "')");

                            db.commit();
                        } catch (Exception ex) {
                            ex.printStackTrace();
                        }
                        db.desconectar();
                        int x = Integer.parseInt(ID);

                        x++;

                        ID = Integer.toString(x);

                        db.desconectar();

                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                    db.desconectar();
                }

            }

        });
        UIManager.put("", null);
        timer.start();

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked

        Dba db = new Dba("./DATA.mdb");
        db.conectar();
        UIManager.put("nimbusOrange", color1);
        // no entindo porque no se cambia el color 
        final Timer timer = new Timer(35, new ActionListener() {
            int progress = 0;
            int maxProgress = 5000;

            @Override
            public void actionPerformed(ActionEvent e) {

                if (progress <= maxProgress) {
                    jProgressBar1.setValue(progress * 100 / maxProgress);
                    progress += 50;
                } else {
                    ((Timer) e.getSource()).stop();
                    JOptionPane.showMessageDialog(jPanel4, "Ejecucion completa sin errores");
                    try {
                        db.query.execute("select [Order ID], [Order Date], [Ship Date], [Ship Mode], [Customer ID] from TenRecord");
                        ResultSet rs = db.query.getResultSet();
                        while (rs.next()) {
                            String a = rs.getString("Order ID");
                            String b = rs.getString("Order Date");
                            String c = rs.getString("Ship Date");
                            String d = rs.getString("Ship Mode");
                            String z = rs.getString("Customer ID");
                            String est = "Order ID: " + a + "\n" + "Order Date: " + b + "\n" + "Ship Date: " + c + "\n" + "Ship Mode: " + d + "\n" + "Customer ID: " + z;
                            C_textArea.setText(est);
                        }
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                    db.desconectar();
                }

            }

        });
        UIManager.put("", null);
        C_textArea.setText("");
        timer.start();

    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked

        Dba db = new Dba("./DATA.mdb");
        db.conectar();
        UIManager.put("nimbusOrange", color2);

        final Timer timer = new Timer(40, new ActionListener() {
            int progress = 0;
            int maxProgress = 5000;

            @Override
            public void actionPerformed(ActionEvent e) {

                if (progress <= maxProgress) {
                    jProgressBar1.setValue(progress * 100 / maxProgress);
                    progress += 50;
                } else {
                    ((Timer) e.getSource()).stop();
                    JOptionPane.showMessageDialog(jPanel4, "Ejecucion completa sin errores");
                    try {
                        db.query.execute("select [Order ID], [Product ID], [Ship Date], Sales, Quantity, Discount, Profit   from TenRecord");
                        ResultSet rs = db.query.getResultSet();
                        while (rs.next()) {
                            String orderID = rs.getString("Order ID");
                            String ProductID = rs.getString("Product ID");
                            String Sales = rs.getString("Sales");
                            String Quantity = rs.getString("Quantity");
                            String Discount = rs.getString("Discount");
                            String Profit = rs.getString("Profit");
                            String est = "Order ID: " + orderID + "\n" + "Product ID: " + ProductID + "\n" + "Sales: " + Sales + "\n" + "Quantity: " + Quantity + "\n" + "Discount: " + Discount + "\n" + "Profit" + Profit;
                            C_textArea.setText(est);
                        }
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                    db.desconectar();

                }
            }
        });
        UIManager.put("", null);
        C_textArea.setText("");
        timer.start();
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked

        Dba db = new Dba("./DATA.mdb");

        db.conectar();
        UIManager.put("nimbusOrange", color3);
        final Timer timer = new Timer(45, new ActionListener() {
            int progress = 0;
            int maxProgress = 5000;

            @Override
            public void actionPerformed(ActionEvent e) {

                if (progress <= maxProgress) {

                    jProgressBar1.setValue(progress * 100 / maxProgress);
                    progress += 50;
                } else {
                    ((Timer) e.getSource()).stop();
                    JOptionPane.showMessageDialog(jPanel4, "Ejecucion completa sin errores");
                    try {
                        db.query.execute("select [Customer ID], [Customer Name], Segment, Country, City, State, [Postal Code], Region from " + "     TenRecord");
                        ResultSet rs = db.query.getResultSet();

                        while (rs.next()) {
                            String CustomerID = rs.getString("Customer ID");
                            String CustomerName = rs.getString("Customer Name");
                            String Segment = rs.getString("Segment");
                            String Country = rs.getString("Country");
                            String City = rs.getString("City");
                            String State = rs.getString("State");
                            String PostalCode = rs.getString("Postal Code");
                            String Region = rs.getString("Region");

                            String est = "Customer ID: " + CustomerID + "\n" + "Customer Name: " + CustomerName + "\n" + "Segment: " + Segment + "\n" + "Country: " + Country + "\n" + "City: " + City + "\n" + "State: " + State + "\n" + "Postal Code : " + PostalCode + "\n" + "Region: " + Region + "\n";

                            C_textArea.setText(est);
                        }
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                    db.desconectar();

                }
            }
        });

        UIManager.put("", null);
        C_textArea.setText("");
        timer.start();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked

        Dba db = new Dba("./DATA.mdb");

        db.conectar();
        UIManager.put("nimbusOrange", color4);
        final Timer timer = new Timer(25, new ActionListener() {

            int progress = 0;
            int maxProgress = 5000;

            @Override
            public void actionPerformed(ActionEvent e) {

                if (progress <= maxProgress) {
                    jProgressBar1.setValue(progress * 100 / maxProgress);
                    progress += 50;
                } else {
                    ((Timer) e.getSource()).stop();

                    try {
                        db.query.execute("select [Product ID], Category, [Sub-Category], [Product Name] from " + "     TenRecord");
                        ResultSet rs = db.query.getResultSet();
                        JOptionPane.showMessageDialog(jPanel4, "Ejecucion completa sin errores");
                        while (rs.next()) {
                            String ProductID = rs.getString("Product ID");
                            String Category = rs.getString("Category");
                            String SubCategory = rs.getString("Sub-Category");
                            String ProductName = rs.getString("Product Name");

                            String rowText = "[Product ID]: " + ProductID + "\n" + "Category: " + Category + "\n" + "[Sub-Category]: " + SubCategory + "\n" + "[Product Name]: " + ProductName + "\n";

                            C_textArea.setText(rowText);
                        }
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                    db.desconectar();

                }
            }
        }
        );
        UIManager.put("", null);
        C_textArea.setText("");
        timer.start();


    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        C_textArea.setText("");

        jProgressBar1.setValue(0);

        UIManager.put("", null);


    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        Dba db = new Dba("./DATA.mdb");

        DefaultTableModel ok = (DefaultTableModel) C_Tabla.getModel();

        String input = JOptionPane.showInputDialog(this, "Ingrese el índice que desea borrar");
        int i = Integer.parseInt(input) - 1;
        int okay = 0;
        String borrar = ok.getValueAt(i, okay).toString();
        db.conectar();

        UIManager.put("nimbusOrange", new Color(0, 153, 0));
        final Timer timer = new Timer(35, new ActionListener() {
            int progress = 0;
            int maxProgress = 5000;

            @Override
            public void actionPerformed(ActionEvent e) {

                if (progress <= maxProgress) {
                    jProgressBar2.setValue(progress * 100 / maxProgress);
                    progress += 50;
                } else {
                    ((Timer) e.getSource()).stop();

                    try {
                        db.query.execute("delete \n "
                                + "from TenRecord " + "\n"
                                + "where [Row ID] = " + "\'" + borrar + "\'");
                        ResultSet okk = db.query.getResultSet();

                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                    db.desconectar();
                }

            }

        });
        timer.start();
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        DefaultTableModel modelo = (DefaultTableModel) C_Tabla.getModel();
        Dba db = new Dba("./DATA.mdb");

        db.conectar();
        UIManager.put("nimbusOrange", color2);
        final Timer timer = new Timer(25, new ActionListener() {

            int progress = 0;
            int maxProgress = 5000;

            @Override
            public void actionPerformed(ActionEvent e) {

                if (progress <= maxProgress) {
                    jProgressBar2.setValue(progress * 100 / maxProgress);
                    progress += 50;
                } else {
                    ((Timer) e.getSource()).stop();
                    JOptionPane.showMessageDialog(jPanel4, "Ejecucion completa sin errores");
                    try {

                        for (int i = 0; i < modelo.getRowCount(); i++) {
                            String rowID = (String) modelo.getValueAt(i, 0);
                            String orderID = (String) modelo.getValueAt(i, 1);
                            String orderDate = (String) modelo.getValueAt(i, 2);
                            String customerID = (String) modelo.getValueAt(i, 3);
                            String country = (String) modelo.getValueAt(i, 4);
                            String city = (String) modelo.getValueAt(i, 5);
                            String productID = (String) modelo.getValueAt(i, 6);
                            String sales = (String) modelo.getValueAt(i, 7);

                            String updateQuery = "update TenRecord set [Order ID] = '" + orderID + "', [Order Date] = '" + orderDate + "', [Customer ID] = '" + customerID + "', Country = '" + country + "', City = '" + city + "', [Product ID] = '" + productID + "', Sales = '" + sales + "' where [Row ID] = '" + rowID + "'";
                            db.query.execute(updateQuery);
                        }

                        db.commit();
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                    db.desconectar();
                }

            }
        }
        );

        timer.start();
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked

        DefaultTableModel modelo = (DefaultTableModel) C_Tabla.getModel();

        Dba db = new Dba("./DATA.mdb");
        db.conectar();
        UIManager.put("nimbusOrange", color2);

        final Timer timer = new Timer(40, new ActionListener() {
            int progress = 0;
            int maxProgress = 5000;

            @Override
            public void actionPerformed(ActionEvent e) {

                if (progress <= maxProgress) {
                    jProgressBar2.setValue(progress * 100 / maxProgress);
                    progress += 50;
                } else {
                    ((Timer) e.getSource()).stop();
                    JOptionPane.showMessageDialog(jPanel4, "Ejecucion completa sin errores");
                    try {
                        db.query.execute("select [Row ID], [Order ID], [Order Date], [Customer ID], Country, City, [Product ID], Sales from TenRecord");
                        ResultSet rs = db.query.getResultSet();

                        while (rs.next()) {
                            Object[] row = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8)};
                            modelo.addRow(row);
                        }
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }

                    db.desconectar();
                }
            }
        });
        timer.start();
        jProgressBar2.setValue(0);

    }//GEN-LAST:event_jButton9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable C_Tabla;
    private javax.swing.JTextArea C_textArea;
    private javax.swing.JTextField Category;
    private javax.swing.JTextField City;
    private javax.swing.JTextField Costumer;
    private javax.swing.JTextField Country;
    private javax.swing.JTextField CustumerN;
    private javax.swing.JTextField Discount;
    private javax.swing.JTextField Order;
    private javax.swing.JTextField OrderD;
    private javax.swing.JTextField Postal;
    private javax.swing.JTextField Product;
    private javax.swing.JTextField ProductN;
    private javax.swing.JTextField Profit;
    private javax.swing.JTextField Quantity;
    private javax.swing.JTextField Region;
    private javax.swing.JTextField SCategory;
    private javax.swing.JTextField Sales;
    private javax.swing.JTextField Segment;
    private javax.swing.JTextField ShipD;
    private javax.swing.JTextField ShipM;
    private javax.swing.JTextField State;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
int progress = 1;
    Color color1 = new Color(0, 153, 0);

    Color color2 = new Color(255, 153, 0);

    Color color3 = new Color(255, 0, 51);

    Color color4 = new Color(51, 51, 255);

}
